name: Deployment Metrics
on: [push, pull_request, pull_request_review, release]

env:
  NODE_VERSION: '14.x'


jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Report Deployment Succeeded
      if: ${{ success() }}
      uses: cto-ai/action@v1.2
      id: ctoai-deployment-succeeded
      with:
        team_id: ${{ secrets.CTOAI_TEAM_ID }}
        token: ${{ secrets.CTOAI_EVENTS_API_TOKEN }}
        event_name: "deployment"
        event_action: "succeeded"
        environment: "production"

