
name: Deployment Metrics
on: [push, pull_request, pull_request_review, release]


- name: Report Deployment Succeeded
  if: ${{ success() }}
  uses: cto-ai/action@v1.2
  id: ctoai-deployment-succeeded
  with:
    team_id: ${{ secrets.CTOAI_TEAM }}
    token: ${{ secrets.CTOAI_TOKEN }}
    event_name: "deployment"
    event_action: "succeeded"
    environment: "production"
- name: Report Deployment Failed
  if: ${{ failure() }}
  uses: cto-ai/action@v1.2
  id: ctoai-deployment-failed
  with:
    team_id: ${{ secrets.CTOAI_TEAM }}
    token: ${{ secrets.CTOAI_TOKEN }}
    event_name: "deployment"
    event_action: "failed"
    environment: "production"