
name: Deployment Metrics

on: [push, pull_request, pull_request_review, release, pull_request_target]

env:
  NODE_VERSION: '15.x'


jobs:
  build-and-deploy:
    - name: Report Deployment Failed
      if: ${{ failure() }}
      uses: cto-ai/action@v1.2
      id: ctoai-deployment-failed
      with:
        team_id: ${{ secrets.CTOAI_TEAM }}
        token: ${{ secrets.CTOAI_TOKEN }}
        event_name: "deployment"
        event_action: "failure"
        environment: "production"
        repo: "https://github.com/thecraftman/cto-ai-insights"